AliyunContainerService/terway

pkg/pool/pool.go, pkg/pool/pool_test.go, pkg/pool/queue.go, pkg/pool/queue_test.go
Release a resource with reverse time. Before the specified time point, resource would not be actually released
=> Add Method ReleaseWithReverse

Dockerfile, policy/0001-terway.patch
=> fix felix build issue

daemon/daemon.go, daemon/eni-multi-ip.go, daemon/eni.go, daemon/k8s.go, pkg/storage/store.go
=> replace the comments in Chinese to English

.circleci/config.yml, policy/policyinit.sh, tests/install_env.sh, tests/stress/stress.sh, tests/test.sh
=> fix shellcheck error

.circleci/config.yml
=> use image from dockerhub

.circleci/config.yml, daemon/daemon.go, daemon/eni-multi-ip.go, daemon/k8s.go, daemon/server.go, daemon/veth.go, deviceplugin/eni.go, examples/maxpods/maxpods.go, main.go, pkg/aliyun/ecs.go, pkg/aliyun/eni.go, pkg/aliyun/metadata.go, pkg/metric/util.go, pkg/pool/pool.go, pkg/pool/pool_test.go, pkg/pool/queue_test.go, pkg/storage/store.go, pkg/tc/tc.go, plugin/driver/drivers.go, plugin/driver/ipvlan.go, plugin/driver/raw_nic.go, plugin/driver/utils.go, plugin/terway/cni.go, rpc/rpc.pb.go
=> fix golint & goimports warnings

.circleci/config.yml, README-zh_CN.md, README.md, docs/design.md
=> add markdownlint

README.md
=> add codecov in README.md

.circleci/config.yml
=> stats coverage of all pkgs

README.md
=> add test command in Readme

daemon/daemon.go, daemon/k8s.go, daemon/server.go, main.go
1. patch the pod ip after allocated the eip
2. add the flag --patch-podip which deside wheather patch podIP to kube-apiserver
=> patch the pod ip after allocated the eip

daemon/daemon.go, daemon/eni-multi-ip.go, daemon/eni.go, daemon/veth.go, pkg/aliyun/aliyun_client_mgr.go, plugin/terway/cni.go, types/config.go
* fix for k8s 1.14 in vpc mode
* use regional domain
* support min & max eni config
* fix error message when obtain ram role
=> Support min/max enis pool config

Gopkg.lock, plugin/driver/ipvlan.go, plugin/driver/ipvlan_test.go, vendor/github.com/vishvananda/netlink/filter.go, vendor/github.com/vishvananda/netlink/filter_linux.go, vendor/github.com/vishvananda/netlink/nl/tc_linux.go
ipvlan: support vm based container and fix bugs
* support vm based container
* fix a wrong match of tc-filter
* set no_arp for slave interface in host namespace
=> ipvlan: support vm based container and fix bugs

pkg/aliyun/ecs.go
Signed-off-by: ziren.wzr <ziren.wzr@alibaba-inc.com>
add more logs in the code for debugging.
=> add debug logs

daemon/daemon.go, daemon/k8s.go, daemon/server.go, main.go
Pod IP patched by terway will be overwritten by kubelet using local cache.
=> Remove patching pod IP which will be overwritten by kubelet

policy/uninstall_policy.sh
policy health port is 9099 always when policy is disabled. Use FELIX_HEALTHPORT to custom health port.
=> custom policy container health port

tests/pod_connection.bats, tests/templates/testcases/network_connection/crosshost.yml, tests/templates/testcases/network_connection/eni.yml, tests/templates/testcases/network_connection/vpc-eni.yml
workaround for https://github.com/kubernetes/kubernetes/issues/73140
=> change node port for testcases

daemon/eni-multi-ip.go
The extra allocate ip requirment already in the ipBacklog:
https://github.com/AliyunContainerService/terway/blob/master/daemon/eni-multi-ip.go#L193-L200
Don't need add to `ipBacklog` again.
=> Fix allocate ip over eni limition

Gopkg.lock, pkg/pool/pool_test.go, vendor/github.com/denverdino/aliyungo/common/client.go, vendor/github.com/denverdino/aliyungo/common/regions.go, vendor/github.com/denverdino/aliyungo/common/types.go, vendor/github.com/denverdino/aliyungo/ecs/networks.go, vendor/github.com/denverdino/aliyungo/ecs/vpcs.go
support internal openapi on recent support region
=> Update aliyungo for internal openapi

pkg/aliyun/ecs.go, pkg/aliyun/utils.go
=> adjust eni operate time

pkg/aliyun/aliyun_client_mgr.go
=> fix vpc client token not refresh

daemon/k8s.go, pkg/tc/tc.go
=> fix: handle parseBandwidth err

daemon/daemon.go, pkg/aliyun/ecs.go, pkg/tracing/tracing.go
Add to event when operate ECS API failed
- DisposeResourceFailed
- AllocResourceFailed
=> add event when failed

daemon/daemon.go, examples/maxpods/maxpods.go, pkg/aliyun/ecs.go, pkg/aliyun/eni.go
issue: https://github.com/AliyunContainerService/terway/issues/151
this is a temporary fix,should consider check addr in netns
=> fix enionly mode crash

Dockerfile.debug
add dlv to terway for debug purpose
=> add debug dockerfile

cli/main.go, plugin/terway/cni.go
=> Handle resolve unix addr error

daemon/daemon.go, daemon/resource_manager.go, go.mod, go.sum, pkg/link/interface.go, pkg/link/interface_unsupport.go, pkg/link/type.go, pkg/sysctl/sysctl.go, plugin/driver/drivers.go, plugin/driver/ipvlan.go, plugin/driver/raw_nic.go, plugin/driver/utils.go, plugin/terway/cni.go
- impl CNI CHECK interface
- period check NIC status
- auto fix NIC down
- miss default route
=> check nic status

docs/host-stack-cidrs.md, plugin/terway/cni.go
add support for host_stack_cidrs in ENIONLY mode. see #162 also.
=> support host_stack_cidrs in ENIONLY mode

daemon/daemon.go, pkg/link/interface.go, pkg/link/interface_unsupport.go, plugin/driver/drivers.go, plugin/driver/utils.go
- auto repaire ip rule when using veth driver
- auto repaire route when using veth driver
- auto gc leaked ip rule when using veth driver
- auto gc leaked route when using ipvlan driver
repair
ipvlan mode 
veth mode
=> repair ip rule

daemon/daemon.go
=> fix deadlock

pkg/pool/pool.go
=> fix token leak when data mismatch

daemon/eni-multi-ip.go, daemon/eni.go, pkg/aliyun/ecs.go
=> change fix sg behave

daemon/daemon.go, daemon/daemon_test.go, pkg/aliyun/ecs.go, pkg/aliyun/errors.go, pkg/link/interface_unsupport.go, pkg/tracing/rpc.go, pkg/tracing/tracing.go, types/types.go
=> fix res mapping not show idle res

README-zh_CN.md, README.md
=> update RAM Permissions matrix

.circleci/config.yml, policy/cilium/02-period-gc-cilium-identity.patch, terway-cilium.yml
=> period gc cilium identity

policy/cilium/02-period-gc-cilium-identity.patch
=> set rv and timeout

daemon/daemon.go
=> fix statefulset leak

pkg/aliyun/ecs.go
=> update check SecurityGroup events

Dockerfile
Before:
user-agent = Kubernetes.Alicloud
After:
user-agent = Kubernetes.Alicloud/0d951a6
=> update user-agent in terway daemon

daemon/eni-multi-ip.go, monitoring/terway-metric-proxy.yml, pkg/aliyun/ecs.go, pkg/aliyun/eni.go, pkg/aliyun/utils.go, pkg/pool/pool.go
=> reduce openAPI cost

plugin/terway/cni.go
=> ignore checking pod with netns not exist

terway.yml
1. bump the apiVersion to apps/v1
2. add the missing required field "selector"
=> Fix the apply DaemonSet failed

terway-cilium.yml, terway-metric.yml, terway-multiip.yml, terway.yml
=> fix APIVersion apps/v1

daemon/daemon.go
fix https://github.com/AliyunContainerService/terway/issues/195
fix self check
=> fix self check

daemon/daemon.go
=> refactor: use sync.map

daemon/daemon.go
Fix comment error. 
Step 3 is here:
https://github.com/AliyunContainerService/terway/blob/c224981eee081b5c0d848307fe3a97d9aa94c1fb/daemon/daemon.go#L260
=> fix comment error

docs/host-stack-cidrs.md, docs/hubble-intergration.md, eni.conf, init.sh, plugin/terway/cni.go, plugin/version/spec.go, terway-cilium.yml, terway-multiip.yml, terway.yml, tests/templates/terway/terway-eni-only.yml, tests/templates/terway/terway-multiip.yml, tests/templates/terway/terway-vpc.yml
fix https://github.com/AliyunContainerService/terway/issues/190
=> Bump cni version to 0.3.1

daemon/daemon.go, daemon/k8s.go, types/config.go, types/k8s.go
ref to #265 
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
=> feat: enable IP reservation for specified pod annotation and custom stateful workloads

Dockerfile, plugin/driver/ipvlan.go, plugin/driver/raw_nic.go, plugin/driver/veth.go, policy/cilium/0006-adapt-CNI-for-IPv6-addr.patch, policy/policyinit.sh, tests/connection_test.go
- set ra for nics
- fix ndp problem with cilium
- enable IPv6 in flex
=> adapt ipv6 for alibaba cloud

daemon/k8s.go, policy/felix/0002-performance-improve.patch
optimize terway and felix performance
=> feat: perf optimize

daemon/eni-multi-ip.go, daemon/k8s.go
This pr fix problem related to terway and terway-controlplane
=> fix problems

daemon/eni-multi-ip.go
Fix terway may panic when batch create eni.
=> fix potential empty eni

plugin/datapath/ipvlan_linux.go
in trunking mode need send traffic to gw, otherwise will face arp problem
=> send traffic to gateway in trunking mode

Dockerfile
ghcr.io/aliyuncontainerservice/terway-policy:20220412-a5beea9@sha256:6e0345d8d4b5ed0d28bc3fade0478dae13e0ff03fec24a51f9c3408699360b09
registry.cn-hongkong.aliyuncs.com/acs/terway:policy-20220412-a5beea9@sha256:6e0345d8d4b5ed0d28bc3fade0478dae13e0ff03fec24a51f9c3408699360b09
=> build: use pre-build policy container

go.sum, tests/connection_test.go, tests/prepare_test.go
skip test in virtual node and not ready node.
=> skip vk and not ready node

daemon/daemon.go, daemon/eip.go, daemon/eni-multi-ip.go, init.sh, pkg/aliyun/aliyun.go, pkg/ipam/ipam.go, pkg/logger/log.go, tests/trunk/perf_test.go, tests/trunk/trunk_test.go
=> several fix

README-zh_CN.md, README.md, daemon/k8s.go, docs/design.md, docs/qos.md, init.sh, plugin/datapath/ipvlan_linux.go, plugin/driver/types/types.go, plugin/terway/cni.go, plugin/terway/cni/runtime_config.go, policy/cilium/0011-add-bandwidth-for-terway-ipvlan.patch, policy/policyinit.sh
- support bandwidth manage for ipvlan ( use EDT ,require kernel 5.10)
- support k8s bandwidth annotations
=> feat: bandwidth manage for ipvlan

tests/prepare_test.go
=> Update backoff steps

Dockerfile, Dockerfile.controlplane, deviceplugin/eni.go, pkg/controller/webhook/mutating.go, pkg/controller/webhook/mutating_default.go, policy/policyinit.sh
=> several update

tests/config_test.go, tests/connection_test.go, tests/prepare_test.go
=> e2e: support custom test image config

policy/policyinit.sh
disable unnecessary checking and enable service topology by default
=> update cilium config

policy/cilium/0009-adapt-1.12.patch
- disable source ip check
- disable host bpf
=> fix hairpin problem

pkg/aliyun/client/vpc.go, pkg/aliyun/client/vsw_default.go, pkg/controller/delegate/del_default.go, pkg/controller/delegate/deleg.go
Set build tags to methods DeleteNetworkInterface and DescribeVSwitchByID
=> Set build tags to methods DeleteNetworkInterface and DescribeVSwitchByID

pkg/aliyun/client/ecs.go, pkg/aliyun/client/types.go, pkg/controller/pool/eni_mgr.go, pkg/controller/vswitch/vswitch.go
=> fix: failed to set resourceGroupID to podENI

policy/cilium/0011-service-Improve-memory-usage-when-handling-update-of.patch, policy/cilium/0012-Fix-restoreServicesLocked-potential-nil-pointer-pani.patch
https://github.com/cilium/cilium/commit/22f5b525ebe1a19f0c9d9d106ff8efa11a9fdf8a
=> cherry-pick service memory usage improve

daemon/eni-multi-ip.go, daemon/eni.go, pkg/controller/pod/pod_controller.go, pkg/controller/webhook/mutating.go
see each commit for more detail
=> fix: several problems

policy/cilium/0015-service-track-backend-state-with-kubernetes.patch
update backend state according to k8s state
https://github.com/cilium/cilium/issues/28094
=> fix: backend state hangs on terminating

plugin/terway/cni_linux.go
update backend state according to k8s state
=> cni: add exec time for cni add

Dockerfile
https://github.com/AliyunContainerService/terway/pull/537
=> policy: update policy image

pkg/aliyun/client/eflo.go
Add OpenAPI latency and resources metrics
=> Eflo metrics

pkg/eni/local.go, pkg/eni/remote.go, pkg/metric/resource_pool.go
terway ip resource metrics collection
=> metrics: collect ip resource metrics

policy/cilium/0031-Ignore-the-link-local-IPv6-addresses-as-it-is-genera.patch
https://github.com/cilium/cilium/pull/33959
=> ignore link local ipv6 addresses

policy/policyinit.sh
add 401 code when apiserver params anonymous-auth set to false.
=> Support ApiServeranonymous-auth

pkg/factory/aliyun/aliyun.go
metadata sync is slow, have to wait it found
=> daemon: add a wait check for mac in ecs metadata

daemon/daemon.go, pkg/k8s/k8s.go, types/daemon/types.go
previous code cleanup has broken the exclusive eni mode
=> fix exclusive eni

Dockerfile, policy/cilium/0032-fix-disable-per-package-lb.patch, policy/cilium/0033-logging.patch, policy/policyinit.sh
backport:
04cc3fbae43cf785d0f383e02f38ba779c585c16
927d6ab6e39477c9561d8fc962bd7257dc9f2262
=> update policy image

pkg/controller/pod/pod_controller.go
=> controlplane: fix re config logic

tests/connecctive_test.go, tests/main_test.go
terway test: support nodeaffinity
=> terway test: support nodeaffinity

policy/cilium/0038-bpf-lxc-defer-CT_INGRESS-entry-creation-for-loopback.patch
[ upstream commit dbf4351c4eff1857cf374886804eb876e970b992 ]
=> bpf: lxc: defer CT_INGRESS entry creation for loopback connections

pkg/aliyun/client/eflo.go, pkg/aliyun/client/eflo_2.go, pkg/aliyun/client/errors/errors.go, pkg/aliyun/client/errors/errors_test.go, pkg/aliyun/client/options.go, pkg/aliyun/client/types.go, pkg/apis/crds/network.alibabacloud.com_nodes.yaml, pkg/apis/crds/register.go, pkg/apis/network.alibabacloud.com/v1beta1/node_types.go, pkg/controller/multi-ip/node/pool.go, pkg/controller/multi-ip/node/pool_test.go, pkg/controller/multi-ip/node/suite_test.go, pkg/controller/node/node.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/suite_test.go, tests/eflo/elfo_test.go
- Add new error codes for Eflo resource not found and private IP quota exceeded
- Replace magic numbers with named error constants in eflo and eflo_2 clients
- Update multi-ip controller to use new error constant for private IP quota- Refactor test environment setup to use a more flexible binary directory search
=> refactor(eflo): enhance error handling and improve code readability

tests/main_test.go, tests/trunk_test.go
=> test(terway): update exclusive ENI test and remove unnecessary labels

cmd/terway-cli/cni.go, cmd/terway-cli/main.go, hack/init.sh
- Add feature gate persistent flag to rootCmd in main.go- Update hack/init.sh to pass extra flags to terway-cli commands
=> refactor(feature-gates): move feature gate handling to main command

tests/main_test.go, tests/trunk_test.go
- Add dedicated namespace for pod networking tests to avoid pollution- Implement waitNamespaceDeleted function for graceful namespace deletion
- Update test flow to create and delete namespace as part of the test
- Adjust pod creation to use the new namespace
- Remove unnecessary namespace update operations
=> test(trunk): improve namespace handling for pod networking tests

daemon/builder.go, daemon/config.go
- Add configuration settings for ENIOnly mode- Adjust logging level for attached ENI information
- Initialize trunk logging
- Set maxENI based on configuration and limits
- Configure pool sizes and IP distribution for ENIOnly mode
=> fix(demon): update config and logging for ENIOnly mode

cmd/terway-controlplane/terway-controlplane.go, daemon/builder.go, examples/maxpods/maxpods.go, go.mod, go.sum, pkg/aliyun/client/limit.go, pkg/aliyun/client/limit_test.go, pkg/controller/common/eni.go, pkg/controller/eni/eni.go, pkg/controller/node/node.go, pkg/controller/pod-eni/eni_controller.go, pkg/controller/pod-eni/eni_controller_test.go, pkg/controller/pod/pod_controller.go, pkg/controller/register.go
- Implement PodENI migration logic to create NetworkInterface CRs- Add migration function to the PodENI controller
- Update tests to cover migration scenarios
- Modify register to include DirectClient in controller context
=> feat/controller: add PodENI migration function

pkg/controller/node/node.go
- Introduce a dedicated delete method for node deletion logic
- Remove redundant code and improve code readability
- Ensure proper handling of finalizers during node deletion
=> refactor(node): optimize node deletion handling

daemon/daemon_test.go, pkg/aliyun/client/types_test.go, pkg/aliyun/credential/clients_test.go, pkg/aliyun/eni/eni_test.go, types/controlplane/annotations_test.go
- Add tests for daemon package- Add tests for aliyun/client package
- Add tests for aliyun/credential package
- Add tests for aliyun/eni package- Add tests for types/controlplane package
=> test: add unit tests for various packages

pkg/controller/pod/pod_controller.go
- Update podENI status to ENIPhaseDetaching for fixed IP
- Add case for ENIPhaseUnbind in the switch statement
=> fix(controller): handle podENI status update for fixed IP

cmd/terway-cli/cni.go, init.sh
- Update daemonset to include BPF maps volume and mount
- Implement BPF filesystem mount check and initialization- Modify init script to handle BPF-related operations
=> feat(init): modify the init logic

cmd/terway-controlplane/terway-controlplane.go, docs/degradation.md, go.mod, go.sum, pkg/controller/multi-ip/node/pool.go, pkg/controller/multi-ip/node/pool_test.go, types/controlplane/config.go, types/controlplane/config_default.go, types/controlplane/config_test.go
- Implement degradation feature to handle cloud provider OpenAPI unavailability- Add two levels of degradation (L0 and L1) for different scenarios
- Update configuration to include degradation settings
- Document degradation design in docs/degradation.md
=> feat(controlplane): add degradation mechanism for Terway

pkg/controller/pod-eni/eni_controller.go
- Update code to handle LinJun nodes specifically
- Improve logic for determining ECS high density nodes
- Refactor node retrieval to support different API versions
=> refactor(pod-eni): optimize node handling for LinJun nodes
