- terway.yml
Fix missing volume config in terway.yml which will cause terway to panic.
> fix: missing volume config in terway.yml

- .circleci/config.yml
- README.md
- policy/0001-terway.patch
> fix misspell scan failure

- daemon/k8s.go
- reduce unnecessary kubernetes api call
PTAL
> reduce unnecessary kubernetes api call

- Gopkg.lock
- pkg/aliyun/ecs.go
- vendor/github.com/denverdino/aliyungo/ecs/disks.go
- vendor/github.com/denverdino/aliyungo/ecs/eni.go
- vendor/github.com/denverdino/aliyungo/ecs/route_tables.go
- vendor/github.com/denverdino/aliyungo/ecs/router_interface.go
- vendor/github.com/denverdino/aliyungo/ecs/snat_entry.go
- vendor/github.com/denverdino/aliyungo/ecs/vpcs.go
- vendor/github.com/denverdino/aliyungo/metadata/client.go
- vendor/github.com/denverdino/aliyungo/util/encoding.go
create network interfaces with a dedicated tag, which can greatly facilitate our life and well itegrate with other systems.
such as: 
- Authorization system (e.g. RAM) can set up some policy based on tags. We trust our code, but we can not guarantee terway 100% bug-free, so we should set up a last defense by authorization policy to avoid terway to delete other people's ENI in some extreme case.  
- We can also manipulate ENIs created by terway via tags:  `aliyun ecs DescribeNetworkInterfaces --RegionId cn-hangzhou --Tag.1.Key creater --Tag.1.Value terway`. this may be helpful when there are lots of ENIs but most of them have no relationship with terway.
> create network interfaces with a dedicated tag

- .circleci/config.yml
- Gopkg.lock
- pkg/aliyun/ecs.go
DescributeInstanceAttribute seems to be in a deprecating progress, and I can't find any official documents about this API on aliyun.com, so maybe we should switch to DescribeInstances.
1. vendor update to match packages and revisions
2. add GetInstanceAttributesType method to ecsImpl which is implemented based on DescribeInstances
3. switch DescributeInstanceAttribute to GetInstanceAttributesType
> switch DescribeInstanceAttribute to DescribeInstances

- daemon/daemon.go
- daemon/k8s.go
CNI timeout on pod initializing:
```
add cmd: error get ip info from grpc call, pod: default-busybox-594898f99b-6f2zg: rpc error: code = Unknown desc = error get pod info for: K8sPodName:"busybox-594898f99b-6f2zg" K8sPodNamespace:"default" K8sPodInfraContainerId:"7137c2e914b03cad9fe81567aca0d139d7096691156a5cb2e32d55bf96c45667" : Get https://172.21.0.1:443/api/v1/namespaces/default/pods/busybox-594898f99b-6f2zg?resourceVersion=0&timeout=1m10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)]
```
The timeout error will encountered continuously for 10-30mins even cni retry times.
After further investigation, the k8s client using `http2` protocol to connect apiserver. `http2` will reuse tcp connection duration http requests. When CNI timeout error, I found the …
> Fix CNI api timeout for a long time

- daemon/daemon.go
- daemon/eni-multi-ip.go
- daemon/eni.go
- pkg/aliyun/ecs.go
- pkg/aliyun/eni.go
- pkg/aliyun/metadata.go
- pkg/pool/pool.go
- types/config.go
- types/types.go
Hi all, 
Terway ENI's intelligent allocation feature for VSwitch/PodIP in multiple VSwitch scenario.
Changes inclue:
1. Add a new field - vswitch_selection_policy, in config file. Values include "ordered" and "random".
"ordered" means allocation for ENI Vswitch/PodIP will be based on the available IP count per vswitch; "random" means that based on random order. 
For new system using this feature, the default policy is "ordered", this will make the most use of IP resources of each VSwitch which has more available IP addresses.
For existing system, the default policy is "random" since existing systems don't have multiple VSwitches configured in their config file, actually "random" and "ordered" don't make much difference in this case.
2. The intelligent selection mechanism's implementation …
> Terway ENI's intelligent allocation feature for VSwitch/PodIP in multiple VSwitch scenario.

- Dockerfile
- Gopkg.lock
- daemon/daemon.go
- daemon/eni-multi-ip.go
- daemon/eni.go
- daemon/eni_test.go
- daemon/k8s.go
- examples/maxpods/maxpods.go
- pkg/aliyun/aliyun_client_mgr.go
- pkg/aliyun/ecs.go
- pkg/aliyun/eni.go
- pkg/aliyun/errors.go
- pkg/pool/pool.go
- pkg/pool/pool_test.go
- plugin/terway/cni.go
- tests/templates/testcases/network_connection/crosshost.yml
- tests/templates/testcases/network_connection/eni.yml
- tests/templates/testcases/network_connection/samehost.yml
- tests/templates/testcases/network_connection/vpc-eni.yml
- tests/templates/testcases/network_policy/network-policy.yml
- tests/templates/testcases/service/loadbalancer.yml
- types/config.go
- vendor/github.com/denverdino/aliyungo/common/client.go
- vendor/github.com/denverdino/aliyungo/ecs/eni.go
* support center encrypted ram authentication
* upgrade felix to 3.5.8
* allocate ips on eni creating, make warming up network resources effective
* recycle completed|failed pod network resources
> Support center ram authentication and some optimize

- plugin/driver/drivers.go
kernel return incomplete rules on FAMILY_ALL.
Then container rule clean up will miss the conflict routes.
Cause system rule leak.
use FAMILY_V4 will return complete ip rule.
relate kernel commit: https://github.com/torvalds/linux/commit/c454673da7c1d6533f40ec2f788023df9af56ebf
```
// ip rule count limit by cb->args[0]:
list_for_each_entry_rcu(ops, &net->rules_ops, list) {
if (idx < cb->args[0] || !try_module_get(ops->owner))
goto skip;
if (dump_rules(skb, cb, ops) < 0)
break;
cb->args[1] = 0;
skip:
idx++;
}
```
> Change RuleList Family to FAMILY_V4 to ensure conflict routes cleanup

- policy/policyinit.sh
cilium add --enable-endpoint-health-checking option to disable health check when chaining with other cni to prevent cilium-health report timeout error on ip in cidr range which does not exist.
> disable endpoint health check for chaining with cilium #135

- Gopkg.lock
- monitoring/terway-metric-proxy.yml
- pkg/aliyun/ecs.go
- vendor/github.com/denverdino/aliyungo/common/client.go
- vendor/github.com/denverdino/aliyungo/ecs/client.go
- vendor/github.com/denverdino/aliyungo/ecs/eni.go
- vendor/github.com/denverdino/aliyungo/ecs/nat_gateway.go
Thanks to ECS API `CreateNetworkInterface`, `AttachNetworkInterface` changed from async to sync mode,
async check can now be removed.
other changes
drop metrics
- WaitForNetworkInterfaceCreate
- AssignPrivateIpAddressesAsync
> adapt ECS API to sync mode

- daemon/eni-multi-ip.go
- pkg/aliyun/ecs.go
- pkg/aliyun/errors.go
- pkg/aliyun/errors_test.go
- pkg/aliyun/utils.go
- pkg/aliyun/utils_test.go
> optimize UnAssignIPForENI reduce unnecessary request

- plugin/terway/cni.go
fix  https://github.com/AliyunContainerService/terway/issues/147
before
```log
default     17m         Warning   FailedCreatePodSandBox   pod/nginx-78c689dfdc-hjjjv       (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "be04b956aba0fd8edce89805d8364afc0d2ed5507f2f07e6fd5312457c8c56b4" network for pod "nginx-78c689dfdc-hjjjv": networkPlugin cni failed to set up pod "nginx-78c689dfdc-hjjjv_default" network: unexpected end of JSON input
```
after
```log
default     5m17s       Warning   FailedCreatePodSandBox   pod/nginx-78c689dfdc-qk7dv       (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container …
```
> fix err is override

- daemon/eni-multi-ip.go
- daemon/eni.go
- pkg/aliyun/ecs.go
- pkg/aliyun/eni.go
- pkg/pool/pool.go
- pkg/pool/pool_test.go
- types/types.go
period check eni's security group is consistent with ecs's security group and try to fix is.
if fix failed ,a event is raised.
this is designed to solve user join node to cluster with previous cluster's node (which  may have residue resource )
> check and fix eni security group

- daemon/daemon.go
vpc mode contain resource use without eni. so should ignore.
e2e ok
> fix vpc mapping

- plugin/driver/ipvlan.go
- plugin/driver/utils.go
Currently when client at node connects to pod, SYN will be directly sent to pod network via ipvlan interface, without going out to VPC. But pod's SYN ACK packets are routed to VPC, instead of go to node directly. This is due to the current setting in the pod, and ipvlan module checks if host ip's MAC address is same as SYN ACK packets' target MAC address.
Now in the pod, we have
```bash
default via 192.168.7.253 dev eth0 onlink
192.168.7.253 dev eth0 lladdr ee:ff:ff:ff:ff:ff REACHABLE
```
A SYN ACK packet to the node will be tagged ee:ff:ff:ff:ff:ff as dest MAC address, not match ipvlan's mac address, so this traffic will not be regards as in-vlan traffic.
https://elixir.bootlin.com/linux/v4.4/source/drivers/net/ipvlan/ipvlan_core.c#L506
In this PR, we create a route for node ip, so mac …
> let pod talk to node directly in ipvlan mode

- pkg/sysctl/sysctl.go
- plugin/driver/drivers.go
- plugin/driver/ipvlan.go
- plugin/driver/raw_nic.go
- plugin/driver/utils.go
- plugin/terway/cni.go
this will set network releated sysconfig to expected.
corrent will set following config
```
IPv4
{"/proc/sys/net/ipv4/conf/%s/forwarding", "1"},
{"/proc/sys/net/ipv4/conf/%s/rp_filter", "0"},
IPv6
{"/proc/sys/net/ipv6/conf/%s/forwarding", "1"},
{"/proc/sys/net/ipv6/conf/%s/disable_ipv6", "0"},
```
> cni: set ip_forward when call cni check

- daemon/k8s.go
fix : when `k8s.aliyun.com/ingress-bandwidth` or `k8s.aliyun.com/egress-bandwidth` is `""` will cause terway panic with error `panic: runtime error: slice bounds out of range [:-1]`, and other pod in the same node stuck in `ContainerCreating` status.
> fix(BandwidthAnno): when k8s.aliyun.com/ingress-bandwidth is "" panic

- policy/cilium/0007-add-flag-to-control-in-cluster-loadBalance.patch
- policy/policyinit.sh
This PR allow user to control whether let traffic go out the cluster.
Set env `IN_CLUSTER_LOADBALANCE=true` to enable it.
The traffic to ExternalIPs/LoadBalanceIP will be short circuit in cluster.
> feat: Add flag to control in cluster loadBalance

- plugin/driver/ipvlan.go
- plugin/driver/netlink.go
- plugin/driver/raw_nic.go
- plugin/driver/utils.go
- plugin/driver/veth.go
- plugin/terway/cni.go
In containerd environment , containers cannot be destroyed when cni return err.
This PR can alleviate this situation.
> fix: Teardown may cause resource leak

- policy/cilium/0008-feat-support-hairpin-with-ipvlan.patch
This PR solve problem for pod to service it's self.
> feat: support hairpin with ipvlan

- docs/terway-trunk.md
- pkg/controller/webhook/mutating.go
If you prefer this feature not work on some namepace , you can config on webhook.
> feat: drop restrict for kube-system namespace

- policy/policyinit.sh
Cilium Hubble failed to start because it can not find a valid tls cert to expose hubble. This pr adds a force disable flag for hubble.
> add force disable tls in hubble args

- policy/cilium/0009-terway-support-kubelet-health-check.patch
- policy/cilium/0010-node-don-t-exclude-IPs-which-is-already-included.patch
cilium with deny all networkpolicy enforced will lead to kubelet unable to do health check
> fix: cilium networkpolicty cause health check problem

- plugin/terway/cni.go
cni return interface fields and portmap plugin will check interface fields
> fix: portmap plugin will not work if sandbox id is empty

- policy/cilium/0009-tcp-rebalance.patch
cherry-pick from https://github.com/cilium/cilium/pull/19451
use default rebalance time 30s
> add tcp rebalance

- terway-cilium.yml
- terway-metric.yml
- terway-multiip.yml
- terway-windows-eni.yml
- terway-windows-eniip.yml
- terway-windows.yml
- terway.yml
1. [isusse](https://github.com/AliyunContainerService/terway/issues/370): The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22
2.  upgrade terway image to v1.2.3, to fix error: plugin terway does not support config version "0.3.1"
> apiextensions.k8s.io/v1beta1 to v1 and upgrade image version to v1.2.3

- pkg/controller/pod-eni/eni_controller.go
- pkg/controller/pod/pod_controller.go
- pkg/controller/pod/predict.go
- pkg/utils/k8s.go
Previous logic will depend on the webhook to tag the pod. 
This will result to pod will never be handled if webhook is installed afted pod is created. 
The pr will make controller work as expected, if webhook is not started yet.
> fix: reconcile every thing at crd mode

- Dockerfile
- Dockerfile.controlplane
- Dockerfile.policy
- policy/cilium/0016-endpoint-Reduce-CPU-and-memory-usage-of-function-mov.patch
- policy/cilium/0017-fix-endpoint-is-lost-during-restore.patch
- policy/policyinit.sh
- fix endpoint may lost during restart cilium
- add a label filter to limit the number of ciliumidentity be generated, user may required to re-create all pods if networkpolicy enforcement is made
> update policy image

- Dockerfile.policy
build policy container with `--build-arg GIT_VERSION=$(git rev-parse --short=8 HEAD 2>/dev/null)`
> build: add GIT_VERSION to track build

- init.sh
> bugfix: Redundant erdma capability in node_capabilities

- cmd/terway-cli/cni.go
- policy/policyinit.sh
always chain cilium cni if policy use ebpf
> policy: support turn-off policy

- pkg/aliyun/client/errors/errors.go
- pkg/controller/multi-ip/node/pool.go
- pkg/controller/pod/pod_controller.go
- pkg/eni/local.go
- pkg/factory/aliyun/aliyun.go
ECS typically returns `InvalidVSwitchId.IpNotEnough` but occasionally the error is `QuotaExceeded.PrivateIpAddress`
> openapi: adapt the QuotaExceeded.PrivateIpAddress code

- pkg/feature/feature.go
We have decided to deprecate ipvlan datapath. This change allows to enable datapathv2 automatically.
> enable auto switch to datapathv2

- pkg/aliyun/client/ecs.go
- pkg/factory/aliyun/aliyun.go
resent eni attach behave changed, it will fail and  rollback to Available , so check is necessary
> validate the eni status to inUse

- daemon/daemon.go
- pkg/eni/local.go
- pkg/eni/local_test.go
- pkg/eni/manager.go
- pkg/eni/manager_test.go
- pkg/eni/types.go
The resource pool will preferentially use returned IPs. allocatingV4 represents the number of IPs requested from the openAPI. In this scenario, this number will not decrease. This typically does not pose an issue, but in some cases, if requests to the openAPI continually fail, it may result in the task running indefinitely.
> add the deadline for the allocating requests

- pkg/controller/node/node.go
- pkg/eni/node_reconcile.go
some instance has member eni , but trunk is not supported
> fix: trunk quantity cal

- daemon/builder.go
- Add error logging when unable to get instance limit from annotation
- Improve error handling and maintain the existing logic flow
> fix(builder): handle instance limit retrieval error

- daemon/builder.go
- daemon/config.go
- daemon/config_test.go
- Retrieve zoneID earlier in setupENIManager to ensure correct vswitch selection
- Pass zoneID to getENIConfig for proper ENI configuration
- Update related test assertions
> fix: initialize zoneID before building ENIConfig

- pkg/eni/node_reconcile.go
- types/k8s.go
- Introduce constant EventConfigError in types/k8s.go for consistent usage
- Update node_reconcile.go to use the new constant for configuration-related events- Improve error handling and logging in the reconciliation process
> refactor(node_reconcile): add constant for config error event

- tests/connective_test.go
- tests/main_test.go
- tests/trunk_test.go
- tests/upgrade_test.go
- Implement comprehensive tests for pod-to-pod connectivity across various scenarios
- Cover different network configurations including host and pod networks
- Test both ClusterIP and NodePort service types with IPv4 and IPv6
- Evaluate traffic policies for NodePort services
- Ensure proper setup and verification of test cases
> test(network): add pod-to-pod connectivity tests

- charts/terway/templates/terwayd/daemonset.yaml
- cmd/terway-cli/cni.go
- hack/init.sh
- Set +o errexit to prevent script termination on error
- Split chroot commands for better error identification
- Update daemonset to include BPF maps volume and mount
> build: improve error handling in init.sh

- deploy/images/terway/Dockerfile
The previously added --exclude is not effective.
Also remove the unused cilium-dbg.
336M    old-terway.tar
272M    terway.tar
Together with the previous commit, we reduce the image size by 64M.
> Shrink container image size fix

- cmd/terway-controlplane/terway-controlplane.go
- cmd/terway-controlplane/terway-controlplane_test.go
- pkg/controller/node/node.go
- Remove node controller import from terway-controlplane
- Update node controller to support centralized IPAM
- Modify Reconcile method to check for centralized IPAM before executing
> refactor(terway): optionalize node controller for centralized IPAM

- cmd/terway-cli/node.go
- cmd/terway-cli/portmap.go
- cmd/terway-cli/portmap_test.go
- go.mod
- plugin/datapath/policy_router_linux.go
- plugin/datapath/policy_router_linux_test.go
- plugin/driver/utils/utils_linux.go
- Add setupHostPort function to configure portmap plugin and network rules
- Implement configureNetworkRules function for iptables and ip rule setup- Include new hostport command in node capabilities
> feat(node): add hostport capability and network setup

- plugin/datapath/policy_router_linux.go
- Remove SCOPE_LINK from routes where it's not needed
> fix(datapath): remove unnecessary IPv6 routes for the policy router

- pkg/backoff/backoff.go
- pkg/backoff/backoff_test.go
- pkg/controller/common/eni.go
- pkg/controller/common/eni_test.go
- pkg/controller/eni/eni.go
- pkg/controller/eni/eni_test.go
- pkg/controller/multi-ip/node/pool.go
- pkg/controller/multi-ip/node/pool_test.go
- pkg/controller/pod-eni/eni_controller.go
- pkg/controller/pod/pod_controller.go
- pkg/eni/crdv2.go
- pkg/eni/crdv2_test.go
- pkg/eni/remote.go
- pkg/factory/aliyun/aliyun.go
- types/controlplane/config_default.go
- types/daemon/config.go
- Introduce ExtendedBackoff struct to support initial delay
- Update backoff map to use ExtendedBackoff instead of wait.Backoff
- Modify ExponentialBackoffWithContext to include initial delay
- Update affected packages to use the new ExtendedBackoff structure
- Add tests for the new initial delay functionality
> feat(backoff): add initial delay support for backoff operations

- go.mod
- go.sum
- Update golang.org/x/oauth2 package from version0.23.0 to0.27.0
- This update may resolve some issues encountered with the previous version
> build(deps): bump golang.org/x/oauth2 from 0.23.0 to 0.27.0

- tests/config_test.go
- tests/main_test.go
- tests/utils_test.go
- Add end-to-end test for IP pool sync period functionality
- Cover scenarios for releasing idle IPs and preheating IPs
- Verify IP release behavior with different sync period configurations
- Ensure proper cleanup and restoration of original configuration
> test(e2e): add IP pool sync period test

- pkg/aliyun/client/ecs.go
- Add error handling for 'InvalidEniId.NotFound' in the ENI delete operation
- Log a success message and return nil when the ENI is already deleted
- Improve error logging by including the request ID
> fix(aliyun): handle not found error for eni delete operation

- pkg/controller/multi-ip/node/pool.go
- pkg/controller/multi-ip/node/pool_test.go
- Implement function to check if the daemon on a node supports runtime
- Add logic to skip IP allocation for pods if daemon does not support node runtime
- Introduce atomic boolean to cache daemon support status per node- Update IP allocation logic to use the new daemon support check
> feat(controller): add check for daemon support of node runtime

- pkg/smc/pnet_test.go
- Implement comprehensive unit tests for SMC-R networking features
- Cover various scenarios including success and failure cases
- Mock system commands and file operations for isolated testing
- Use testify/assert for test assertions
- Include tests for ensuring SMC-R support, configuring devices, and handling errors
> test(smc): add unit tests for SMC-R networking functionality

- cmd/terway-cli/cni_linux.go
- cmd/terway-cli/cni_linux_test.go
- cmd/terway-cli/cni_test.go
- Use node capabilities to determine if cilium chainer is present
- Check for existence of cilium_net link as a fallback- Add unit tests for allowEBPFNetworkPolicy function
- Update integration tests to cover new behavior
> fix(networkpolicy): improve cilium chainer detection and handling

- cmd/terway/main.go
- daemon/server.go
- hack/init.sh
- pkg/feature/feature.go
- Introduce new feature gate for writing CNI configuration first
- Implement feature gate parsing and setting in main.go
- Add condition to skip CNI configuration writing in server.go
- Update hack/init.sh script to handle WriteCNIConfFirst flag
- Register WriteCNIConfFirst feature in feature.go
> feat(terway): add WriteCNIConfFirst feature gate
